### ISSUE TITLE
Updating and improving the documentation

### ISSUE THREAD

**Issue by ampersarnie** [bigbite/wp-cypress#76]
Documentation is not complete and requires some improvement in some areas. I'll be using this issue to track any documentation ready for the release of v1.0.0.

- [ ]  Setting the WP [locale configuration](https://github.com/bigbite/wp-cypress/wiki/Configuration-Options) (see: #56).
- [ ]  Setting up seeder clean routines (see: #70)
	- [ ]  [Extend the code examples and API](https://github.com/bigbite/wp-cypress/wiki/Seeds-and-Fixtures).
	- [ ]  [CLI arguments and commands](https://github.com/bigbite/wp-cypress/wiki/Cypress-Commands).
- [ ]  Setting [the PHP version](https://github.com/bigbite/wp-cypress/wiki/Configuration-Options) (see: #69)
- [ ]  [Manual user switching](https://github.com/bigbite/wp-cypress/wiki/Auth-and-Users). (see: #62)
- [ ]  Exposing the [db port configuration](https://github.com/bigbite/wp-cypress/wiki/Configuration-Options) (see: #60)
- [ ]  [Examples page](https://github.com/bigbite/wp-cypress/wiki/Examples)
